name: Release Drafter

on:
  push:
    tags:
      - 'v*'

jobs:
  check-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check master branch
        id: check
        run: |
          SHA=$(git log -n1 --format=format:"%H")
          git checkout production 
          git merge-base --is-ancestor $SHA HEAD
  release-draft:
    runs-on: ubuntu-latest
    needs: check-master
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Run release drafter
        id: release-drafter
        uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ steps.get_version.outputs.VERSION }}
          name: ${{ steps.get_version.outputs.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
