name: Staging Deployment

on:
  push:
    branches:
      - staging

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: staging

      - name: Heroku login
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Add heroku staging remote
        run: heroku git:remote --app "${HEROKU_STAGING_APP_NAME}"
        env:
          HEROKU_STAGING_APP_NAME: ${{ secrets.HEROKU_STAGING_APP_NAME }}

      - name: Push to heroku master
        run: |
          git checkout "${GITHUB_REF##*/}"
          git push -f heroku HEAD:master


